// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Csft struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type Post struct {
	ID          uuid.UUID
	Title       string
	Slug        string
	Content     string
	Excerpt     sql.NullString
	Author      sql.NullString
	PublishedAt sql.NullTime
	Thumbnail   sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Tags        []string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	FirstName    sql.NullString
	LastName     sql.NullString
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
