// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                    uuid.UUID
	AccountId             string
	ProviderId            string
	UserId                uuid.UUID
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IdToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Post struct {
	ID          uuid.UUID
	Title       string
	Slug        string
	Content     string
	Excerpt     sql.NullString
	Author      sql.NullString
	PublishedAt sql.NullTime
	Thumbnail   sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Tags        []string
}

type Session struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IpAddress sql.NullString
	UserAgent sql.NullString
	UserId    uuid.UUID
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	EmailVerified bool
	Image         sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Verification struct {
	ID         uuid.UUID
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
