// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkSessionByID = `-- name: CheckSessionByID :one
SELECT
    "userId",
    "expiresAt"
FROM
    SESSION
WHERE
    token = $1
`

type CheckSessionByIDRow struct {
	UserId    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CheckSessionByID(ctx context.Context, token string) (CheckSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, checkSessionByID, token)
	var i CheckSessionByIDRow
	err := row.Scan(&i.UserId, &i.ExpiresAt)
	return i, err
}
