name: cd
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: true

      - name: install dependencies
        run: go mod download

      - name: build app
        run: CGO_ENABLED=0 GOOS=linux go build -o realtorbackend .

      - name: build image
        run: docker build -t dgarcia51/realtorbackend:${{ github.sha }} .

      - name: tag image
        run: docker tag dgarcia51/realtorbackend:${{ github.sha }} dgarcia51/realtorbackend:latest

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: push image
        run: |
          docker push dgarcia51/realtorbackend:${{ github.sha }}
          docker push dgarcia51/realtorbackend:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - build-and-push
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo PORT=${{ secrets.PORT }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo TOKEN_SECRET=${{ secrets.TOKEN_SECRET }} >> .env
          echo APP_PASSWORD=${{ secrets.APP_PASSWORD }} >> .env
          echo FUB_API_KEY=${{ secrets.FUB_API_KEY }} >> .env
          echo X_SYSTEM=${{ secrets.X_SYSTEM }} >> .env
          echo X_SYSTEM_KEY=${{ secrets.X_SYSTEM_KEY }} >> .env
          echo S3_REGION=${{ secrets.S3_REGION }} >> .env
          echo S3_BUCKET=${{ secrets.S3_BUCKET }} >> .env
          echo AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo BREVO_API_KEY=${{ secrets.BREVO_API_KEY }} >> .env

      - name: deploy stack
        uses: cssnr/stack-deploy-action@v1
        with:
          name: realtorbackend 
          file: docker-compose.yml
          host: soldbyghost.com
          user: ghost
          ssh_key: ${{ secrets.SSH_KEY }}
          env_file: .env
