name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      # Run go fmt and check for unformatted files
      - name: Check formatting with go fmt
        run: |
          unformatted=$(go fmt ./...)
          if [ -n "$unformatted" ]; then
            echo "The following files need formatting:"
            echo "$unformatted"
            exit 1
          fi
          echo "All files are properly formatted."

      # Install and run gosec for security checks, excluding G101
      - name: Run security checks with gosec
        run: |
          # Install gosec
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          # Run gosec, excluding G101
          gosec -exclude=G101 ./...

      # Run tests
      - name: Run tests
        run: go test -v ./...
